2020-09-23 19:28:39.703137: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-23 19:28:39.725784: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3999980000 Hz
2020-09-23 19:28:39.726143: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c78356c1b0 executing computations on platform Host. Devices:
2020-09-23 19:28:39.726160: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-09-23 19:28:40.708414: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 5642400000 exceeds 10% of system memory.
[*] training: read vectorized features
WARNING: EMBER feature version 1 were computed using lief version 0.8.3-18d5b75
WARNING:   lief version 0.9.0- found instead. There may be slight inconsistencies
WARNING:   in the feature calculations.
[*] testing: read vectorized features
WARNING: EMBER feature version 1 were computed using lief version 0.8.3-18d5b75
WARNING:   lief version 0.9.0- found instead. There may be slight inconsistencies
WARNING:   in the feature calculations.
900000
False
[*] Building neural network
[*] Compiling neural network
[*] Training neural network...
Train on 600000 samples, validate on 200000 samples
Epoch 1/3
600000/600000 - 28s - loss: 27744.4266 - accuracy: 0.5048 - val_loss: 1.1685 - val_accuracy: 0.5000
Epoch 2/3
600000/600000 - 28s - loss: 106.6685 - accuracy: 0.4999 - val_loss: 0.8623 - val_accuracy: 0.5000
Epoch 3/3
600000/600000 - 28s - loss: 22.5851 - accuracy: 0.5006 - val_loss: 0.6931 - val_accuracy: 0.5000
(200000, 2)
training lightGBM model
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    lgbm_model = ember.train_model(datadir, params, 2)
  File "/home/yongbak/anaconda3/envs/malware_detector/lib/python3.6/site-packages/ember/__init__.py", line 205, in train_model
    X_train, y_train = read_vectorized_features(data_dir, "train", feature_version)
  File "/home/yongbak/anaconda3/envs/malware_detector/lib/python3.6/site-packages/ember/__init__.py", line 104, in read_vectorized_features
    X_train = np.memmap(X_train_path, dtype=np.float32, mode="r", shape=(N, ndim))
  File "/home/yongbak/anaconda3/envs/malware_detector/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
